services:
  - type: web
    name: present-foods-api
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18
      - key: ADMIN_PHONE
        value: 2348082563629
